version: '3.3'
services: 
    db:
        image: mysql:latest
        restart: always
        environment: 
            MYSQL_DATABASE: 'mysql_stovfl_survey'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'r00t-password'
        ports: 
            - '3306:3306'
        expose: 
            - '3306'
        volumes:
            # - my-db:/var/lib/mysql
            - my-db:/mysql_stovfl_survey
                # /Users/frederico/stackoverflow-dev-survey
volumes:
    my-db: 
